package PT.Gui;

import PT.Control.DataAlumno;
import PT.Control.DataInscripcion;
import PT.Control.DataMateria;
import PT.Modelo.Alumno;
import PT.Modelo.Inscripcion;
import PT.Modelo.Materia;
import PT.main.main;
import javax.swing.JOptionPane;

/**
 *
 * @author Heisen
 */
public class GUIAgregarInscripcion extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUIAgregarInscripcion
     */
    public GUIAgregarInscripcion() {
        DataAlumno dataAlumno = new DataAlumno();
        DataMateria dataMateria = new DataMateria();

        initComponents();
        setResizable(false);

        for (Alumno alumno : dataAlumno.readAllAlumno()) {

            jBoxAlumno.addItem(alumno);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTitulo = new javax.swing.JLabel();
        jLDni = new javax.swing.JLabel();
        jLMateria = new javax.swing.JLabel();
        jBCancelar = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jBoxMateria = new javax.swing.JComboBox<>();
        jBoxAlumno = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jLTitulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLTitulo.setText("MODIFICAR INSCRIPCION");

        jLDni.setText("Alumno");

        jLMateria.setText(" Materia");

        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jBoxMateria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));

        jBoxAlumno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        jBoxAlumno.setToolTipText("");
        jBoxAlumno.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jBoxAlumnoItemStateChanged(evt);
            }
        });
        jBoxAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoxAlumnoActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLMateria)
                                .addComponent(jLDni)
                                .addComponent(jBoxMateria, 0, 336, Short.MAX_VALUE)
                                .addComponent(jBoxAlumno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(67, 67, 67))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(17, 17, 17))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLTitulo)
                            .addGap(119, 119, 119)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBGuardar)
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLTitulo)
                .addGap(18, 18, 18)
                .addComponent(jLDni)
                .addGap(18, 18, 18)
                .addComponent(jBoxAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLMateria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBoxMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCancelar)
                    .addComponent(jBGuardar))
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        DataInscripcion dataInscripcion = new DataInscripcion();

        int aux = JOptionPane.showConfirmDialog(rootPane, "¿Está seguro que desea guardar esta inscripcion?");
        if (aux == 0) {
            Inscripcion inscripcion = new Inscripcion();
            inscripcion.setId_alumno(((Alumno) jBoxAlumno.getSelectedItem()).getId_alumno());
            inscripcion.setId_materia(((Materia) jBoxMateria.getSelectedItem()).getId_materia());
            dataInscripcion.crearInscripcion(inscripcion);

        }
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBoxAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoxAlumnoActionPerformed
        DataAlumno dataAlumno = new DataAlumno();
        DataMateria dataMateria = new DataMateria();
        DataInscripcion dataInscripcion = new DataInscripcion();
        int id_alumno=((Alumno)jBoxAlumno.getSelectedItem()).getId_alumno();
        jBoxMateria.removeAllItems();
        for (Materia materia : dataInscripcion.obtenerMateriasNoInscriptas(id_alumno)) {
            jBoxMateria.addItem(materia);
        }        // TODO add your handling code here:
        System.out.println("asaa");
    }//GEN-LAST:event_jBoxAlumnoActionPerformed

    private void jBoxAlumnoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jBoxAlumnoItemStateChanged

    }//GEN-LAST:event_jBoxAlumnoItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JComboBox<Object> jBoxAlumno;
    private javax.swing.JComboBox<Object> jBoxMateria;
    private javax.swing.JLabel jLDni;
    private javax.swing.JLabel jLMateria;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
