/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package PT.Gui;

import PT.Control.DataAlumno;
import PT.Modelo.Alumno;
import java.time.LocalDate;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author dante
 */
public class GUIAgregarAlumno extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUIAgregarAlumno
     */
    public GUIAgregarAlumno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JTFDNIAlumno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JTFNombreAlumno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JTFApellidoAlumno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        DateChooser = new com.toedter.calendar.JDateChooser();
        JBCancelarA = new javax.swing.JButton();
        JBLimpiarA = new javax.swing.JButton();
        JBGuardarA = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Agregar Alumno");

        jLabel2.setText("DNI");

        jLabel3.setText("Nombre");

        jLabel4.setText("Apellido");

        JTFApellidoAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFApellidoAlumnoActionPerformed(evt);
            }
        });

        jLabel5.setText("Fecha de nacimiento");

        JBCancelarA.setText("Cancelar");
        JBCancelarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCancelarAActionPerformed(evt);
            }
        });

        JBLimpiarA.setText("Limpiar");
        JBLimpiarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBLimpiarAActionPerformed(evt);
            }
        });

        JBGuardarA.setText("Guardar");
        JBGuardarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBGuardarAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(DateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(JTFApellidoAlumno)
                                    .addComponent(JTFNombreAlumno)
                                    .addComponent(JTFDNIAlumno)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JBCancelarA)
                                .addGap(94, 94, 94)
                                .addComponent(JBLimpiarA)
                                .addGap(99, 99, 99)
                                .addComponent(JBGuardarA)))))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JTFDNIAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JTFNombreAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JTFApellidoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(DateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBCancelarA)
                    .addComponent(JBLimpiarA)
                    .addComponent(JBGuardarA))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTFApellidoAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFApellidoAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFApellidoAlumnoActionPerformed

    private void JBGuardarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBGuardarAActionPerformed
        int aux = JOptionPane.showConfirmDialog(rootPane, "¿Está seguro que desea guardar este alumno?");
        if (aux == 0) {
            Alumno a = new Alumno();
            int d = DateChooser.getCalendar().get(Calendar.DAY_OF_MONTH);
            int m = DateChooser.getCalendar().getTime().getMonth() + 1;
            int an = DateChooser.getCalendar().getTime().getYear() + 1900;
            a.setDni(JTFDNIAlumno.getText());
            a.setNombre(JTFNombreAlumno.getText());
            a.setApellido(JTFApellidoAlumno.getText());
            a.setFecha_nacimiento(LocalDate.of(an, m, d));

            DataAlumno DA = new DataAlumno();
            DA.createAlumno(a);

            JTFDNIAlumno.setText("");
            JTFNombreAlumno.setText("");
            JTFApellidoAlumno.setText("");
            JBGuardarA.setEnabled(false);
        } else if (aux == 1) {
            JTFDNIAlumno.setText("");
            JTFNombreAlumno.setText("");
            JTFApellidoAlumno.setText("");
            JBGuardarA.setEnabled(false);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_JBGuardarAActionPerformed

    private void JBLimpiarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBLimpiarAActionPerformed
        JTFDNIAlumno.setText("");
        JTFNombreAlumno.setText("");
        JTFApellidoAlumno.setText("");
    }//GEN-LAST:event_JBLimpiarAActionPerformed

    private void JBCancelarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCancelarAActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_JBCancelarAActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateChooser;
    private javax.swing.JButton JBCancelarA;
    private javax.swing.JButton JBGuardarA;
    private javax.swing.JButton JBLimpiarA;
    private javax.swing.JTextField JTFApellidoAlumno;
    private javax.swing.JTextField JTFDNIAlumno;
    private javax.swing.JTextField JTFNombreAlumno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
