/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PT.Gui;

import PT.Control.DataMateria;
import PT.Modelo.Materia;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author Moon
 */
public class GUIAgregarMateria extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUIAgregarMateria
     */
    public GUIAgregarMateria() {
        initComponents();
        jBGuardar.setEnabled(false);
        this.setPreferredSize(new Dimension(500, 375));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLNombre = new javax.swing.JLabel();
        jLAnio = new javax.swing.JLabel();
        jTFNombreMateria = new javax.swing.JTextField();
        jTFAnioMateria = new javax.swing.JTextField();
        jBCancelar = new javax.swing.JButton();
        jBLimpiar = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLTitulo2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setMinimumSize(null);
        setName(""); // NOI18N
        setNormalBounds(null);
        setPreferredSize(new java.awt.Dimension(638, 392));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLNombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLNombre.setForeground(new java.awt.Color(51, 51, 51));
        jLNombre.setText("Nombre");
        getContentPane().add(jLNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        jLAnio.setBackground(new java.awt.Color(0, 0, 0));
        jLAnio.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLAnio.setForeground(new java.awt.Color(51, 51, 51));
        jLAnio.setText("Año");
        getContentPane().add(jLAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        jTFNombreMateria.setBackground(new java.awt.Color(255, 255, 255));
        jTFNombreMateria.setForeground(new java.awt.Color(204, 204, 204));
        jTFNombreMateria.setText("Ingrese el nombre de la materia");
        jTFNombreMateria.setBorder(null);
        jTFNombreMateria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFNombreMateriaFocusGained(evt);
            }
        });
        jTFNombreMateria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTFNombreMateriaMousePressed(evt);
            }
        });
        jTFNombreMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNombreMateriaActionPerformed(evt);
            }
        });
        jTFNombreMateria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFNombreMateriaKeyReleased(evt);
            }
        });
        getContentPane().add(jTFNombreMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 304, 30));

        jTFAnioMateria.setBackground(new java.awt.Color(255, 255, 255));
        jTFAnioMateria.setForeground(new java.awt.Color(204, 204, 204));
        jTFAnioMateria.setText("Ingrese el año de la materia (solo números)");
        jTFAnioMateria.setBorder(null);
        jTFAnioMateria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTFAnioMateriaMousePressed(evt);
            }
        });
        jTFAnioMateria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFAnioMateriaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFAnioMateriaKeyTyped(evt);
            }
        });
        getContentPane().add(jTFAnioMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 300, 30));

        jBCancelar.setForeground(new java.awt.Color(51, 51, 51));
        jBCancelar.setText("Cancelar");
        jBCancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jBCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 70, 30));

        jBLimpiar.setForeground(new java.awt.Color(51, 51, 51));
        jBLimpiar.setText("Limpiar");
        jBLimpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(jBLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 70, 30));

        jBGuardar.setForeground(new java.awt.Color(51, 51, 51));
        jBGuardar.setText("Guardar");
        jBGuardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jBGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 70, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 304, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 310, 20));

        jPanel1.setBackground(new java.awt.Color(38, 79, 135));

        jLTitulo2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLTitulo2.setForeground(new java.awt.Color(255, 255, 255));
        jLTitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTitulo2.setText("Agregar Materia");

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLTitulo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(435, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFNombreMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNombreMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNombreMateriaActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        int aux = JOptionPane.showConfirmDialog(rootPane, "¿Está seguro que desea guardar esta materia?");
        if (aux == 0) {
            Materia m = new Materia();
            m.setNombre(jTFNombreMateria.getText());
            m.setAnio(Integer.parseInt(jTFAnioMateria.getText()));

            DataMateria DM = new DataMateria(); //Creamos DataMateria - se crea la conexión
            DM.createMateria(m);

            jTFNombreMateria.setText("");
            jTFAnioMateria.setText("");
            jBGuardar.setEnabled(false);
        } else if (aux == 1) {
            jTFNombreMateria.setText("");
            jTFAnioMateria.setText("");
            jBGuardar.setEnabled(false);
        }
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarActionPerformed
        jTFNombreMateria.setText("");
        jTFAnioMateria.setText("");
        jBGuardar.setEnabled(false);
    }//GEN-LAST:event_jBLimpiarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jTFAnioMateriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFAnioMateriaKeyTyped
        Character c = evt.getKeyChar();
        if (!Character.isDigit(c) && !c.equals('\b') && !c.equals('\t') && !c.equals('\n')) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se pueden ingresar numeros en "
                    + "este campo");
        }
        if (jTFAnioMateria.getText().length() > 3) {
            evt.consume();
        }
    }//GEN-LAST:event_jTFAnioMateriaKeyTyped

    private void jTFAnioMateriaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFAnioMateriaKeyReleased
        habilitarBoton();
    }//GEN-LAST:event_jTFAnioMateriaKeyReleased

    private void jTFNombreMateriaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFNombreMateriaKeyReleased
        habilitarBoton();
    }//GEN-LAST:event_jTFNombreMateriaKeyReleased

    private void jTFNombreMateriaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFNombreMateriaMousePressed
        jTFNombreMateria.setText("");
        jTFNombreMateria.setForeground(Color.DARK_GRAY);
    }//GEN-LAST:event_jTFNombreMateriaMousePressed

    private void jTFAnioMateriaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFAnioMateriaMousePressed
        jTFAnioMateria.setText("");
        jTFAnioMateria.setForeground(Color.DARK_GRAY);
    }//GEN-LAST:event_jTFAnioMateriaMousePressed

    private void jTFNombreMateriaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFNombreMateriaFocusGained

    }//GEN-LAST:event_jTFNombreMateriaFocusGained

    public void habilitarBoton() {
        if (!jTFAnioMateria.getText().isEmpty() && !jTFNombreMateria.getText().isEmpty()) {
            jBGuardar.setEnabled(true);
        } else {
            jBGuardar.setEnabled(false);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBLimpiar;
    private javax.swing.JLabel jLAnio;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLTitulo2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTFAnioMateria;
    private javax.swing.JTextField jTFNombreMateria;
    // End of variables declaration//GEN-END:variables
}
