/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PT.Gui;

import PT.Control.DataAlumno;
import PT.Modelo.Alumno;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Moon
 */
public class GUIBuscarAlumno extends javax.swing.JInternalFrame {
    
    private DefaultTableModel modelo;

    /**
     * Creates new form GUIBuscarAlumnos
     */
    public GUIBuscarAlumno() {
        initComponents();
        jBBuscar.setEnabled(false); 
        jTFBuscarID.setEnabled(false); 
        modelo = new DefaultTableModel();
        armarCabecera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTAlumnos = new javax.swing.JTable();
        jBBuscar = new javax.swing.JButton();
        jBVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jRBBuscar = new javax.swing.JRadioButton();
        jTFBuscarID = new javax.swing.JTextField();
        jRBMostrarTodos = new javax.swing.JRadioButton();

        jTAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "DNI", "Fecha de Nacimiento"
            }
        ));
        jScrollPane1.setViewportView(jTAlumnos);

        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jBVolver.setText("Volver");
        jBVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVolverActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("BUSCAR ALUMNO");

        jRBBuscar.setText("Buscar por ID");
        jRBBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jRBBuscarMousePressed(evt);
            }
        });
        jRBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBBuscarActionPerformed(evt);
            }
        });

        jRBMostrarTodos.setText("Mostrar todos");
        jRBMostrarTodos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jRBMostrarTodosMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRBMostrarTodos)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRBBuscar)
                        .addGap(30, 30, 30)
                        .addComponent(jTFBuscarID, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(185, 185, 185))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBBuscar)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBVolver))
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBBuscar)
                    .addComponent(jTFBuscarID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscar))
                .addGap(18, 18, 18)
                .addComponent(jRBMostrarTodos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBVolver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        borrarFilasTabla(); 
        DataAlumno DM = new DataAlumno();
        Alumno auxiliar = new Alumno(); 
        auxiliar = DM.readAlumno(Integer.parseInt(jTFBuscarID.getText())); 
        modelo.addRow(new Object[]{auxiliar.getDni(), auxiliar.getNombre(), auxiliar.getApellido(), auxiliar.getFecha_nacimiento()}); 
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jRBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBBuscarActionPerformed

    private void jRBMostrarTodosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBMostrarTodosMousePressed
        jTFBuscarID.setText(""); 
        jTFBuscarID.setEnabled(false); 
        jRBBuscar.setSelected(false); 
        borrarFilasTabla();
        if (!jRBMostrarTodos.isSelected()) { 
            DataAlumno DA = new DataAlumno();
            for (Alumno alumno : DA.readAllAlumno()) {
                modelo.addRow(new Object[]{alumno.getDni(), alumno.getNombre(), alumno.getApellido(), alumno.getFecha_nacimiento()});
            }
        }
    }//GEN-LAST:event_jRBMostrarTodosMousePressed

    private void jRBBuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBBuscarMousePressed
        jTFBuscarID.setEnabled(true); 
        jBBuscar.setEnabled(true); 
        jRBMostrarTodos.setSelected(false); 
        borrarFilasTabla(); 

        if (jRBBuscar.isSelected()) {
            jTFBuscarID.setEnabled(false); 
            jBBuscar.setEnabled(false);
        }
    }//GEN-LAST:event_jRBBuscarMousePressed

    private void jBVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVolverActionPerformed
        dispose();
    }//GEN-LAST:event_jBVolverActionPerformed


    private void armarCabecera() {
        ArrayList<Object> columnas = new ArrayList();
        columnas.add("DNI");
        columnas.add("Nombre");
        columnas.add("Apellido");
        columnas.add("Fecha de nacimiento");

        for (Object columna : columnas) {
            modelo.addColumn(columna);
        }

        jTAlumnos.setModel(modelo);
    }
    
    private void borrarFilasTabla() {
        if (modelo != null) {
            int a = modelo.getRowCount() -1;

            for (int i = a; i >= 0; i--) {
                modelo.removeRow(i);
            }
        }

    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRBBuscar;
    private javax.swing.JRadioButton jRBMostrarTodos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTAlumnos;
    private javax.swing.JTextField jTFBuscarID;
    // End of variables declaration//GEN-END:variables
}
