/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PT.Gui;

import PT.Control.DataMateria;
import PT.Modelo.Materia;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Moon
 */
public class GUIBuscarMateria extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo; //Creamos el modelo de la tabla

    /**
     * Creates new form GUIBuscarMaterias
     */
    public GUIBuscarMateria() {
        initComponents();
        jBBuscar.setEnabled(false); //Deshabilitamos el botón buscar por default
        jTFBuscarID.setEnabled(false); //Deshabilitamos por default el campo de buscar ID
        modelo = new DefaultTableModel();
        armarCabecera(); //Llamámos al método para asignarle nombres a las cabeceras de la tabla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTFBuscarID = new javax.swing.JTextField();
        jRBMostrarTodos = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTMateria = new javax.swing.JTable();
        jBBuscar = new javax.swing.JButton();
        jBVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jRBBuscar = new javax.swing.JRadioButton();

        jTFBuscarID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFBuscarIDKeyTyped(evt);
            }
        });

        jRBMostrarTodos.setText("Mostrar todas");
        jRBMostrarTodos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jRBMostrarTodosMousePressed(evt);
            }
        });

        jTMateria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "", ""
            }
        ));
        jScrollPane1.setViewportView(jTMateria);

        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jBVolver.setText("Volver");
        jBVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVolverActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("BUSCAR MATERIA");

        jRBBuscar.setText("Buscar por legajo");
        jRBBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jRBBuscarMousePressed(evt);
            }
        });
        jRBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRBMostrarTodos)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRBBuscar)
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jTFBuscarID, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBBuscar)
                            .addComponent(jBVolver))))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBBuscar)
                    .addComponent(jTFBuscarID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscar))
                .addGap(18, 18, 18)
                .addComponent(jRBMostrarTodos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBVolver)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRBMostrarTodosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBMostrarTodosMousePressed
        jTFBuscarID.setText(""); //Reseteamos el campo de buscar ID
        jTFBuscarID.setEnabled(false); //y lo deshabilitamos
        jRBBuscar.setSelected(false); //Des-seleccionamos el botón de buscar por ID
        borrarFilasTabla(); //Reseteamos la tabla (si no se vuelven a poner las materias abajo si volvés a presionar)
        //Condicional para que solo muestre las mats cuando esté seleccionado y no cuando sea un click para des-seleccionar
        if (!jRBMostrarTodos.isSelected()) { 
            DataMateria DM = new DataMateria();
            for (Materia materia : DM.readAllMateria()) {
                modelo.addRow(new Object[]{materia.getNombre(), materia.getAnio()});
            }
        }
    }//GEN-LAST:event_jRBMostrarTodosMousePressed

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        borrarFilasTabla(); //Reseteamos la tabla
        DataMateria DM = new DataMateria();
        Materia auxiliar = new Materia(); //Creamos una materia auxiliar y le cargamos la materia seleccionada
        auxiliar = DM.readMateria(Integer.parseInt(jTFBuscarID.getText())); //a través del ID
        modelo.addRow(new Object[]{auxiliar.getNombre(), auxiliar.getAnio()}); //la añadimos a la tabla
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jRBBuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBBuscarMousePressed
        jTFBuscarID.setEnabled(true); //Habilita el text field del ID
        jBBuscar.setEnabled(true); //Habilita el botón buscar
        jRBMostrarTodos.setSelected(false); //Des-selecciona el Mostrar Todas
        borrarFilasTabla(); // Limpia la tabla

        if (jRBBuscar.isSelected()) {
            jTFBuscarID.setEnabled(false); //Deshabilita el text field si no está seleccionado el Buscar
            jBBuscar.setEnabled(false);
        }

    }//GEN-LAST:event_jRBBuscarMousePressed

    private void armarCabecera() {
        ArrayList<Object> columnas = new ArrayList();
        columnas.add("Nombre");
        columnas.add("Año");

        for (Object columna : columnas) {
            modelo.addColumn(columna);
        }

        jTMateria.setModel(modelo);
    }

    private void borrarFilasTabla() {
        if (modelo != null) {
            int a = modelo.getRowCount() - 1;

            for (int i = a; i >= 0; i--) {
                modelo.removeRow(i);
            }
        }

    }


    private void jRBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBBuscarActionPerformed

    private void jBVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVolverActionPerformed
        dispose();
    }//GEN-LAST:event_jBVolverActionPerformed

    private void jTFBuscarIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFBuscarIDKeyTyped
        Character c = evt.getKeyChar();
        if (!Character.isDigit(c) && !c.equals('\b') && !c.equals('\t') && !c.equals('\n')) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se pueden ingresar numeros en "
                    + "este campo");
        }
        if (jTFBuscarID.getText().length() > 3) {
            evt.consume();
        }
    }//GEN-LAST:event_jTFBuscarIDKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRBBuscar;
    private javax.swing.JRadioButton jRBMostrarTodos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFBuscarID;
    private javax.swing.JTable jTMateria;
    // End of variables declaration//GEN-END:variables
}
