/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PT.Gui;

import PT.Control.DataAlumno;
import PT.Modelo.Alumno;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Moon
 */
public class GUIBuscarAlumno extends javax.swing.JInternalFrame {
    
    private DefaultTableModel modelo;

    /**
     * Creates new form GUIBuscarAlumnos
     */
    public GUIBuscarAlumno() {
        initComponents();
        jBBuscar.setEnabled(false); 
        jTFBuscarID.setEnabled(false); 
        modelo = new DefaultTableModel();
        armarCabecera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTAlumnos = new javax.swing.JTable();
        jBBuscar = new javax.swing.JButton();
        jBVolver = new javax.swing.JButton();
        jRBBuscar = new javax.swing.JRadioButton();
        jTFBuscarID = new javax.swing.JTextField();
        jRBMostrarTodos = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLTitulo2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(726, 432));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTAlumnos.setBackground(new java.awt.Color(255, 255, 255));
        jTAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "DNI", "Fecha de Nacimiento"
            }
        ));
        jScrollPane1.setViewportView(jTAlumnos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, 130));

        jBBuscar.setForeground(new java.awt.Color(51, 51, 51));
        jBBuscar.setText("Buscar");
        jBBuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jBBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, 90, 30));

        jBVolver.setForeground(new java.awt.Color(51, 51, 51));
        jBVolver.setText("Volver");
        jBVolver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVolverActionPerformed(evt);
            }
        });
        getContentPane().add(jBVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 90, 30));

        jRBBuscar.setBackground(new java.awt.Color(255, 255, 255));
        jRBBuscar.setForeground(new java.awt.Color(51, 51, 51));
        jRBBuscar.setText("Buscar por legajo");
        jRBBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jRBBuscarMousePressed(evt);
            }
        });
        jRBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jRBBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, -1, -1));

        jTFBuscarID.setBackground(new java.awt.Color(255, 255, 255));
        jTFBuscarID.setForeground(new java.awt.Color(204, 204, 204));
        jTFBuscarID.setText("Ingrese el número de legajo aquí");
        jTFBuscarID.setBorder(null);
        jTFBuscarID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTFBuscarIDMousePressed(evt);
            }
        });
        getContentPane().add(jTFBuscarID, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 300, 30));

        jRBMostrarTodos.setBackground(new java.awt.Color(255, 255, 255));
        jRBMostrarTodos.setForeground(new java.awt.Color(51, 51, 51));
        jRBMostrarTodos.setText("Mostrar todos");
        jRBMostrarTodos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jRBMostrarTodosMousePressed(evt);
            }
        });
        getContentPane().add(jRBMostrarTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        jPanel1.setBackground(new java.awt.Color(38, 79, 135));

        jLTitulo2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLTitulo2.setForeground(new java.awt.Color(255, 255, 255));
        jLTitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTitulo2.setText("Buscar Alumno");

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLTitulo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(345, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 410));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 300, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        borrarFilasTabla(); 
        DataAlumno DM = new DataAlumno();
        Alumno auxiliar = new Alumno(); 
        auxiliar = DM.readAlumno(Integer.parseInt(jTFBuscarID.getText())); 
        modelo.addRow(new Object[]{auxiliar.getDni(), auxiliar.getNombre(), auxiliar.getApellido(), auxiliar.getFecha_nacimiento()}); 
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jRBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBBuscarActionPerformed

    private void jRBMostrarTodosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBMostrarTodosMousePressed
        jTFBuscarID.setText(""); 
        jTFBuscarID.setEnabled(false); 
        jRBBuscar.setSelected(false); 
        borrarFilasTabla();
        if (!jRBMostrarTodos.isSelected()) { 
            DataAlumno DA = new DataAlumno();
            for (Alumno alumno : DA.readAllAlumno()) {
                modelo.addRow(new Object[]{alumno.getDni(), alumno.getNombre(), alumno.getApellido(), alumno.getFecha_nacimiento()});
            }
        }
    }//GEN-LAST:event_jRBMostrarTodosMousePressed

    private void jRBBuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBBuscarMousePressed
        jTFBuscarID.setEnabled(true); 
        jBBuscar.setEnabled(true); 
        jRBMostrarTodos.setSelected(false); 
        borrarFilasTabla(); 

        if (jRBBuscar.isSelected()) {
            jTFBuscarID.setEnabled(false); 
            jBBuscar.setEnabled(false);
        }
    }//GEN-LAST:event_jRBBuscarMousePressed

    private void jBVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVolverActionPerformed
        dispose();
    }//GEN-LAST:event_jBVolverActionPerformed

    private void jTFBuscarIDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFBuscarIDMousePressed
        jTFBuscarID.setText("");
        jTFBuscarID.setForeground(Color.DARK_GRAY);
    }//GEN-LAST:event_jTFBuscarIDMousePressed


    private void armarCabecera() {
        ArrayList<Object> columnas = new ArrayList();
        columnas.add("DNI");
        columnas.add("Nombre");
        columnas.add("Apellido");
        columnas.add("Fecha de nacimiento");

        for (Object columna : columnas) {
            modelo.addColumn(columna);
        }

        jTAlumnos.setModel(modelo);
    }
    
    private void borrarFilasTabla() {
        if (modelo != null) {
            int a = modelo.getRowCount() -1;

            for (int i = a; i >= 0; i--) {
                modelo.removeRow(i);
            }
        }

    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBVolver;
    private javax.swing.JLabel jLTitulo2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRBBuscar;
    private javax.swing.JRadioButton jRBMostrarTodos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTAlumnos;
    private javax.swing.JTextField jTFBuscarID;
    // End of variables declaration//GEN-END:variables
}
