/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package PT.Gui;

import PT.Control.DataAlumno;
import PT.Control.DataInscripcion;
import PT.Control.DataMateria;
import PT.Modelo.Alumno;
import PT.Modelo.Inscripcion;
import PT.Modelo.Materia;
import PT.main.main;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.xml.crypto.Data;

/**
 *
 * @author Heisen
 */
public class GUIModificarInscripcion extends javax.swing.JInternalFrame {

    DefaultTableModel modeloTabla = new DefaultTableModel();

    public GUIModificarInscripcion() {
        DataMateria dataMateria = new DataMateria();
        DataAlumno dataAlumno = new DataAlumno();

        initComponents();
        this.setPreferredSize(new Dimension(900, 600));

        pack();
        jBInscribir.setEnabled(false);
        jBDesinscribir.setEnabled(false);

        jRBInscriptas.setOpaque(false);
        jRBNoInscriptas.setOpaque(false);

        setResizable(false);
        //llenado combobox con alumnos      
        for (Alumno alumno : dataAlumno.readAllAlumno()) {

            jCBAlumno.addItem(alumno);

        }
//colocando cabezera
        ArrayList<Object> columnas = new ArrayList<Object>();
        columnas.add("Cod");
        columnas.add("Materia");
        columnas.add("Año");

        for (Object it : columnas) {
            modeloTabla.addColumn(it);
        }
//setieando el modelo a la tabla
        jTable.setModel(modeloTabla);
        jCBAlumno.setSelectedItem(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTitulo = new javax.swing.JLabel();
        jBDesinscribir = new javax.swing.JButton();
        jBCancelar1 = new javax.swing.JButton();
        jCBAlumno = new javax.swing.JComboBox<>();
        jRBInscriptas = new javax.swing.JRadioButton();
        jRBNoInscriptas = new javax.swing.JRadioButton();
        jBInscribir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();

        setClosable(true);
        setIconifiable(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setOpaque(true);
        setVisible(true);
        getContentPane().setLayout(null);

        jLTitulo.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        jLTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTitulo.setText("Inscribir/Desinscribir de Materias");
        getContentPane().add(jLTitulo);
        jLTitulo.setBounds(0, 20, 900, 48);

        jBDesinscribir.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jBDesinscribir.setText("Desinscribir");
        jBDesinscribir.setAlignmentX(1.0F);
        jBDesinscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDesinscribirActionPerformed(evt);
            }
        });
        getContentPane().add(jBDesinscribir);
        jBDesinscribir.setBounds(370, 520, 150, 32);

        jBCancelar1.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jBCancelar1.setText("Cancelar");
        jBCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelar1ActionPerformed(evt);
            }
        });
        getContentPane().add(jBCancelar1);
        jBCancelar1.setBounds(706, 520, 130, 32);

        jCBAlumno.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jCBAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBAlumnoActionPerformed(evt);
            }
        });
        getContentPane().add(jCBAlumno);
        jCBAlumno.setBounds(270, 140, 350, 31);

        jRBInscriptas.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jRBInscriptas.setText("Desinscribir");
        jRBInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBInscriptasActionPerformed(evt);
            }
        });
        getContentPane().add(jRBInscriptas);
        jRBInscriptas.setBounds(570, 200, 120, 20);

        jRBNoInscriptas.setBackground(jLabel1.getBackground());
        jRBNoInscriptas.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jRBNoInscriptas.setText("Inscribir");
        jRBNoInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBNoInscriptasActionPerformed(evt);
            }
        });
        getContentPane().add(jRBNoInscriptas);
        jRBNoInscriptas.setBounds(210, 200, 130, 20);

        jBInscribir.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jBInscribir.setText("Inscribir");
        jBInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInscribirActionPerformed(evt);
            }
        });
        getContentPane().add(jBInscribir);
        jBInscribir.setBounds(50, 520, 120, 32);

        jTable.setBackground(new java.awt.Color(204, 204, 204));
        jTable.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Materia", "Año"
            }
        ));
        jTable.setToolTipText("");
        jScrollPane1.setViewportView(jTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 240, 790, 232);

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel2.setText("Alumno");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(410, 100, 70, 20);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/fondo.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 610);

        jRadioButton1.setText("jRadioButton1");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(710, 160, 98, 21);

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInscribirActionPerformed
        DataInscripcion dataInscripcion = new DataInscripcion();
        int fila = jTable.getSelectedRow();
        if (fila >= 0) {
            int id_materia = (int) modeloTabla.getValueAt(fila, 0);
            int id_alumno = ((Alumno) jCBAlumno.getSelectedItem()).getId_alumno();
            System.out.println(modeloTabla.getValueAt(fila, 0));
            Inscripcion inscripcion = new Inscripcion(id_materia, id_alumno, -1);
            dataInscripcion.crearInscripcion(inscripcion);
        }
        jRBInscriptas.setSelected(false);
        jRBNoInscriptas.setSelected(false);
        modeloTabla.setNumRows(0);
        jCBAlumno.setSelectedItem(null);
        jBInscribir.setEnabled(false);

    }//GEN-LAST:event_jBInscribirActionPerformed

    private void jRBNoInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBNoInscriptasActionPerformed
        DataInscripcion dataInscripcion = new DataInscripcion();

        jRBInscriptas.setSelected(false);
        jBInscribir.setEnabled(true);
        jBDesinscribir.setEnabled(false);

        modeloTabla.setNumRows(0);

        int id_alumno = ((Alumno) jCBAlumno.getSelectedItem()).getId_alumno();

        ArrayList<Materia> auxArray = new ArrayList<>();
        auxArray.addAll(dataInscripcion.obtenerMateriasNoInscriptas(id_alumno));

        for (Materia materia : auxArray) {

            modeloTabla.addRow(new Object[]{materia.getId_materia(), materia.getNombre(), materia.getAnio()});
        }
    }//GEN-LAST:event_jRBNoInscriptasActionPerformed

    private void jRBInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBInscriptasActionPerformed
        jRBNoInscriptas.setSelected(false);
        jBInscribir.setEnabled(false);
        jBDesinscribir.setEnabled(true);

        DataInscripcion dataInscripcion = new DataInscripcion();

        modeloTabla.setNumRows(0);

        int id_alumno = ((Alumno) jCBAlumno.getSelectedItem()).getId_alumno();

        ArrayList<Materia> auxArray = new ArrayList<>();
        auxArray.addAll(dataInscripcion.obtenerMateriasInscriptas(id_alumno));

        for (Materia materia : auxArray) {

            modeloTabla.addRow(new Object[]{materia.getId_materia(), materia.getNombre(), materia.getAnio()});
        }
    }//GEN-LAST:event_jRBInscriptasActionPerformed

    private void jCBAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBAlumnoActionPerformed
        jRBInscriptas.setSelected(false);
        jRBNoInscriptas.setSelected(false);
        if(jCBAlumno.getSelectedItem()==null){
        jRBInscriptas.setEnabled(false);
        jRBNoInscriptas.setEnabled(false);
        }else{
            jRBInscriptas.setEnabled(true);
             jRBNoInscriptas.setEnabled(true);
        }
    }//GEN-LAST:event_jCBAlumnoActionPerformed

    private void jBCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelar1ActionPerformed
        dispose();
    }//GEN-LAST:event_jBCancelar1ActionPerformed

    private void jBDesinscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDesinscribirActionPerformed
        DataInscripcion dataInscripcion = new DataInscripcion();
        ArrayList<Inscripcion> inscripciones = new ArrayList<>();
        inscripciones.addAll(dataInscripcion.obtenerTodasInscripciones());
        int fila = jTable.getSelectedRow();
        int id_materia = (int) modeloTabla.getValueAt(fila, 0);
        int id_alumno = ((Alumno) jCBAlumno.getSelectedItem()).getId_alumno();
        for (Inscripcion aux : inscripciones) {
            if (aux.getId_alumno() == id_alumno && aux.getId_materia() == id_materia) {
                dataInscripcion.deleteInscripcion(aux.getId_inscripcion());
            }
        }
        jRBInscriptas.setSelected(false);
        jRBNoInscriptas.setSelected(false);
        modeloTabla.setNumRows(0);
         jCBAlumno.setSelectedItem(null);
         jBDesinscribir.setEnabled(false);
    }//GEN-LAST:event_jBDesinscribirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar1;
    private javax.swing.JButton jBDesinscribir;
    private javax.swing.JButton jBInscribir;
    private javax.swing.JComboBox<Object> jCBAlumno;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRBInscriptas;
    private javax.swing.JRadioButton jRBNoInscriptas;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
}
