/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package PT.Gui;

import PT.Control.DataAlumno;
import PT.Modelo.Alumno;
import java.time.LocalDate;
import java.util.Calendar;

/**
 *
 * @author dante
 */
public class GUIModificarAlumno extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUIModificarAlumno
     */
    public GUIModificarAlumno() {
        initComponents();
        DataAlumno DA = new DataAlumno();
        for (Alumno alumno : DA.readAllAlumno()) {
            JComboModAlum.addItem(alumno);
            JComboDelAlum.addItem(alumno);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JComboModAlum = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JTFModApellidoAlum = new javax.swing.JTextField();
        JTFModNombreAlum = new javax.swing.JTextField();
        JTFDNIModAlum = new javax.swing.JTextField();
        DateChooserMod = new com.toedter.calendar.JDateChooser();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        JComboDelAlum = new javax.swing.JComboBox<>();
        JBCancelarModA = new javax.swing.JButton();
        JBLimpiarModA = new javax.swing.JButton();
        JBGuardarModA = new javax.swing.JButton();
        JBCancelarDelA = new javax.swing.JButton();
        JBBorrarDelA = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Modificar Alumno");

        jLabel2.setText("Elija el alumno que desea modificar");

        jLabel3.setText("DNI");

        jLabel4.setText("Nombre");

        jLabel5.setText("Apellido");

        jLabel6.setText("Fecha de nacimiento");

        JTFModApellidoAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFModApellidoAlumActionPerformed(evt);
            }
        });

        JTFModNombreAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFModNombreAlumActionPerformed(evt);
            }
        });

        JTFDNIModAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFDNIModAlumActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("Dar de baja alumno");

        jLabel8.setText("Elija el alumno que desea dar de baja");

        JBCancelarModA.setText("Cancelar");
        JBCancelarModA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCancelarModAActionPerformed(evt);
            }
        });

        JBLimpiarModA.setText("Limpiar");
        JBLimpiarModA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBLimpiarModAActionPerformed(evt);
            }
        });

        JBGuardarModA.setText("Guardar");
        JBGuardarModA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBGuardarModAActionPerformed(evt);
            }
        });

        JBCancelarDelA.setText("Cancelar");
        JBCancelarDelA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCancelarDelAActionPerformed(evt);
            }
        });

        JBBorrarDelA.setText("Borrar");
        JBBorrarDelA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBBorrarDelAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(84, 84, 84)
                            .addComponent(JBCancelarModA)
                            .addGap(115, 115, 115)
                            .addComponent(JBLimpiarModA)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JBGuardarModA))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(63, 63, 63)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(JComboModAlum, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JTFDNIModAlum, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel6))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(DateChooserMod, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                                        .addComponent(JTFModNombreAlum)
                                        .addComponent(JTFModApellidoAlum))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JBCancelarDelA)
                            .addComponent(jLabel8))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(JComboDelAlum, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(JBBorrarDelA)))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(JComboModAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addComponent(JTFDNIModAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JTFModNombreAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JTFModApellidoAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(DateChooserMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBCancelarModA)
                    .addComponent(JBLimpiarModA)
                    .addComponent(JBGuardarModA))
                .addGap(4, 4, 4)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(JComboDelAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBCancelarDelA)
                    .addComponent(JBBorrarDelA))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTFModNombreAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFModNombreAlumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFModNombreAlumActionPerformed

    private void JTFDNIModAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFDNIModAlumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFDNIModAlumActionPerformed

    private void JTFModApellidoAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFModApellidoAlumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFModApellidoAlumActionPerformed

    private void JBLimpiarModAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBLimpiarModAActionPerformed
        JTFDNIModAlum.setText("");
        JTFModNombreAlum.setText("");
        JTFModApellidoAlum.setText("");
    }//GEN-LAST:event_JBLimpiarModAActionPerformed

    private void JBCancelarModAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCancelarModAActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_JBCancelarModAActionPerformed

    private void JBCancelarDelAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCancelarDelAActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_JBCancelarDelAActionPerformed

    private void JBGuardarModAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBGuardarModAActionPerformed
        DataAlumno DA = new DataAlumno();
        int d = DateChooserMod.getCalendar().get(Calendar.DAY_OF_MONTH);
        int m = DateChooserMod.getCalendar().getTime().getMonth() + 1;
        int an = DateChooserMod.getCalendar().getTime().getYear() + 1900;
        DA.updateAlumno(((Alumno) JComboModAlum.getSelectedItem()), JTFModApellidoAlum.getText(), JTFModNombreAlum.getText(), JTFModApellidoAlum.getText(), java.sql.Date.valueOf(LocalDate.of(an, m, d)));// TODO add your handling code here:
    }//GEN-LAST:event_JBGuardarModAActionPerformed

    private void JBBorrarDelAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBBorrarDelAActionPerformed
        DataAlumno DA = new DataAlumno();
        DA.deleteAlumno(((Alumno)JComboDelAlum.getSelectedItem()).getId_alumno());
    }//GEN-LAST:event_JBBorrarDelAActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateChooserMod;
    private javax.swing.JButton JBBorrarDelA;
    private javax.swing.JButton JBCancelarDelA;
    private javax.swing.JButton JBCancelarModA;
    private javax.swing.JButton JBGuardarModA;
    private javax.swing.JButton JBLimpiarModA;
    private javax.swing.JComboBox<Alumno> JComboDelAlum;
    private javax.swing.JComboBox<Alumno> JComboModAlum;
    private javax.swing.JTextField JTFDNIModAlum;
    private javax.swing.JTextField JTFModApellidoAlum;
    private javax.swing.JTextField JTFModNombreAlum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
