/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package PT.Gui;

import PT.Control.DataAlumno;
import PT.Control.DataInscripcion;
import PT.Control.DataMateria;
import PT.Modelo.Alumno;
import PT.Modelo.Inscripcion;
import PT.Modelo.Materia;
import PT.main.main;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.xml.crypto.Data;

/**
 *
 * @author Heisen
 */
public class GUIModificarInscripcion extends javax.swing.JInternalFrame {

    DefaultTableModel modeloTabla = new DefaultTableModel();

    public GUIModificarInscripcion() {
        DataMateria dataMateria = new DataMateria();
        DataAlumno dataAlumno = new DataAlumno();
        initComponents();
        jBInscribir.setEnabled(false);
        jBDesinscribir.setEnabled(false);
        setResizable(false);

        for (Alumno alumno : dataAlumno.readAllAlumno()) {

            jCBAlumno.addItem(alumno);

        }
        for (Materia materia : dataMateria.readAllMateria()) {

        }
//colocando cabezera
        ArrayList<Object> columnas = new ArrayList<Object>();
        columnas.add("Cod");
        columnas.add("Materia");
        columnas.add("Año");

        for (Object it : columnas) {
            modeloTabla.addColumn(it);
        }
//setieando el modelo a la tabla
        jTable.setModel(modeloTabla);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTitulo = new javax.swing.JLabel();
        jLMateria = new javax.swing.JLabel();
        jLAlumno = new javax.swing.JLabel();
        jBDesinscribir = new javax.swing.JButton();
        jBCancelar1 = new javax.swing.JButton();
        jCBAlumno = new javax.swing.JComboBox<>();
        jRBInscriptas = new javax.swing.JRadioButton();
        jRBNoInscriptas = new javax.swing.JRadioButton();
        jBInscribir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();

        jLTitulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLTitulo.setText("MODIFICAR INSCRIPCION");

        jLMateria.setText("Materias");

        jLAlumno.setText("Ingrese el alumno del cual quiere modificar la inscripcion");

        jBDesinscribir.setText("Desinscribir");
        jBDesinscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDesinscribirActionPerformed(evt);
            }
        });

        jBCancelar1.setText("Cancelar");
        jBCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelar1ActionPerformed(evt);
            }
        });

        jCBAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBAlumnoActionPerformed(evt);
            }
        });

        jRBInscriptas.setText("Inscriptas");
        jRBInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBInscriptasActionPerformed(evt);
            }
        });

        jRBNoInscriptas.setText("No Inscriptas");
        jRBNoInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBNoInscriptasActionPerformed(evt);
            }
        });

        jBInscribir.setText("Inscribir");
        jBInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInscribirActionPerformed(evt);
            }
        });

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Materia", "Año"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jRBInscriptas)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jRBNoInscriptas))
                                .addComponent(jCBAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBInscribir)
                                .addGap(61, 61, 61)
                                .addComponent(jBDesinscribir)
                                .addGap(58, 58, 58)
                                .addComponent(jBCancelar1)))
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLTitulo)
                        .addGap(152, 152, 152))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLMateria)
                        .addGap(242, 242, 242))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLAlumno)
                .addGap(24, 24, 24)
                .addComponent(jCBAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLMateria)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRBInscriptas)
                    .addComponent(jRBNoInscriptas))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBInscribir)
                    .addComponent(jBDesinscribir)
                    .addComponent(jBCancelar1))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRBInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBInscriptasActionPerformed
        jRBNoInscriptas.setSelected(false);
        jBInscribir.setEnabled(false);
        jBDesinscribir.setEnabled(true);

        DataInscripcion dataInscripcion = new DataInscripcion();

        modeloTabla.setNumRows(0);

        int id_alumno = ((Alumno) jCBAlumno.getSelectedItem()).getId_alumno();

        ArrayList<Materia> auxArray = new ArrayList<>();
        auxArray.addAll(dataInscripcion.obtenerMateriasInscriptas(id_alumno));

        for (Materia materia : auxArray) {

            modeloTabla.addRow(new Object[]{materia.getId_materia(), materia.getNombre(), materia.getAnio()});
        }
    }//GEN-LAST:event_jRBInscriptasActionPerformed

    private void jRBNoInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBNoInscriptasActionPerformed
        DataInscripcion dataInscripcion = new DataInscripcion();

        jRBInscriptas.setSelected(false);
        jBInscribir.setEnabled(true);
        jBDesinscribir.setEnabled(false);

        modeloTabla.setNumRows(0);

        int id_alumno = ((Alumno) jCBAlumno.getSelectedItem()).getId_alumno();

        ArrayList<Materia> auxArray = new ArrayList<>();
        auxArray.addAll(dataInscripcion.obtenerMateriasNoInscriptas(id_alumno));

        for (Materia materia : auxArray) {

            modeloTabla.addRow(new Object[]{materia.getId_materia(), materia.getNombre(), materia.getAnio()});
        }
    }//GEN-LAST:event_jRBNoInscriptasActionPerformed

    private void jBInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInscribirActionPerformed
        DataInscripcion dataInscripcion = new DataInscripcion();
        int fila = jTable.getSelectedRow();
        if (fila >= 0) {
            int id_materia = (int) modeloTabla.getValueAt(fila, 0);
            int id_alumno = ((Alumno) jCBAlumno.getSelectedItem()).getId_alumno();
            System.out.println(modeloTabla.getValueAt(fila, 0));
            Inscripcion inscripcion = new Inscripcion(id_materia, id_alumno, 0);
            dataInscripcion.crearInscripcion(inscripcion);
        }
        jRBInscriptas.setSelected(false);
        jRBNoInscriptas.setSelected(false);
        modeloTabla.setNumRows(0);


    }//GEN-LAST:event_jBInscribirActionPerformed

    private void jCBAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBAlumnoActionPerformed
        jRBInscriptas.setSelected(false);
        jRBNoInscriptas.setSelected(false);
    }//GEN-LAST:event_jCBAlumnoActionPerformed

    private void jBDesinscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDesinscribirActionPerformed
        DataInscripcion dataInscripcion = new DataInscripcion();
        ArrayList<Inscripcion> inscripciones = new ArrayList<>();
        inscripciones.addAll(dataInscripcion.obtenerTodasInscripciones());
        int fila = jTable.getSelectedRow();
        int id_materia = (int) modeloTabla.getValueAt(fila, 0);
        int id_alumno = ((Alumno) jCBAlumno.getSelectedItem()).getId_alumno();
        for (Inscripcion aux : inscripciones) {
            if (aux.getId_alumno() == id_alumno && aux.getId_materia() == id_materia) {
                dataInscripcion.deleteInscripcion(aux.getId_inscripcion());
            }
        }
        jRBInscriptas.setSelected(false);
        jRBNoInscriptas.setSelected(false);
        modeloTabla.setNumRows(0);

    }//GEN-LAST:event_jBDesinscribirActionPerformed

    private void jBCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelar1ActionPerformed
        dispose();
    }//GEN-LAST:event_jBCancelar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar1;
    private javax.swing.JButton jBDesinscribir;
    private javax.swing.JButton jBInscribir;
    private javax.swing.JComboBox<Object> jCBAlumno;
    private javax.swing.JLabel jLAlumno;
    private javax.swing.JLabel jLMateria;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JRadioButton jRBInscriptas;
    private javax.swing.JRadioButton jRBNoInscriptas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
}
