/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PT.Gui;

/**
 *
 * @author Moon
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jDesktopPaneMain = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu_Materias = new javax.swing.JMenu();
        jmiAgregarMateria = new javax.swing.JMenuItem();
        jmiModificarMateria = new javax.swing.JMenuItem();
        jmiBuscarMateria = new javax.swing.JMenuItem();
        jMenu_Alumnos = new javax.swing.JMenu();
        jmiAgregarAlumno = new javax.swing.JMenuItem();
        jmiModificarAlumno = new javax.swing.JMenuItem();
        jmiBuscarAlumno = new javax.swing.JMenuItem();
        jMenu_Inscripciones = new javax.swing.JMenu();
        jmiEliminarInscripcion = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPaneMainLayout = new javax.swing.GroupLayout(jDesktopPaneMain);
        jDesktopPaneMain.setLayout(jDesktopPaneMainLayout);
        jDesktopPaneMainLayout.setHorizontalGroup(
            jDesktopPaneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPaneMainLayout.setVerticalGroup(
            jDesktopPaneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jMenu_Materias.setText("Materias");
        jMenu_Materias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu_MateriasMousePressed(evt);
            }
        });

        jmiAgregarMateria.setText("Agregar");
        jmiAgregarMateria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmiAgregarMateriaMousePressed(evt);
            }
        });
        jmiAgregarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAgregarMateriaActionPerformed(evt);
            }
        });
        jMenu_Materias.add(jmiAgregarMateria);

        jmiModificarMateria.setText("Modificar / Dar de baja");
        jmiModificarMateria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmiModificarMateriaMousePressed(evt);
            }
        });
        jMenu_Materias.add(jmiModificarMateria);

        jmiBuscarMateria.setText("Buscar materia");
        jmiBuscarMateria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmiBuscarMateriaMousePressed(evt);
            }
        });
        jMenu_Materias.add(jmiBuscarMateria);

        jMenuBar2.add(jMenu_Materias);

        jMenu_Alumnos.setText("Alumnos");

        jmiAgregarAlumno.setText("Agregar");
        jmiAgregarAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmiAgregarAlumnoMousePressed(evt);
            }
        });
        jmiAgregarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAgregarAlumnoActionPerformed(evt);
            }
        });
        jMenu_Alumnos.add(jmiAgregarAlumno);

        jmiModificarAlumno.setText("Modificar / Dar de baja");
        jmiModificarAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmiModificarAlumnoMousePressed(evt);
            }
        });
        jMenu_Alumnos.add(jmiModificarAlumno);

        jmiBuscarAlumno.setText("Buscar alumno");
        jmiBuscarAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmiBuscarAlumnoMousePressed(evt);
            }
        });
        jMenu_Alumnos.add(jmiBuscarAlumno);

        jMenuBar2.add(jMenu_Alumnos);

        jMenu_Inscripciones.setText("Inscripciones");

        jmiEliminarInscripcion.setText("Modificar/Dar de Baja");
        jmiEliminarInscripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmiEliminarInscripcionMousePressed(evt);
            }
        });
        jmiEliminarInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEliminarInscripcionActionPerformed(evt);
            }
        });
        jMenu_Inscripciones.add(jmiEliminarInscripcion);

        jMenuBar2.add(jMenu_Inscripciones);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneMain)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneMain)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiAgregarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAgregarAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiAgregarAlumnoActionPerformed

    private void jMenu_MateriasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_MateriasMousePressed

    }//GEN-LAST:event_jMenu_MateriasMousePressed

    private void jmiAgregarMateriaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiAgregarMateriaMousePressed
        GUIAgregarMateria agregarMat = new GUIAgregarMateria();
        agregarMat.setVisible(true);
        jDesktopPaneMain.add(agregarMat);
    }//GEN-LAST:event_jmiAgregarMateriaMousePressed

    private void jmiAgregarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAgregarMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiAgregarMateriaActionPerformed

    private void jmiAgregarAlumnoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiAgregarAlumnoMousePressed
        GUIAgregarAlumno agregarAlum = new GUIAgregarAlumno();
        agregarAlum.setVisible(true);
        jDesktopPaneMain.add(agregarAlum);        // TODO add your handling code here:
    }//GEN-LAST:event_jmiAgregarAlumnoMousePressed

    private void jmiEliminarInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEliminarInscripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiEliminarInscripcionActionPerformed

    private void jmiEliminarInscripcionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiEliminarInscripcionMousePressed
        GUIModificarInscripcion modInsc = new GUIModificarInscripcion();
        modInsc.setVisible(true);
        jDesktopPaneMain.add(modInsc);
    }//GEN-LAST:event_jmiEliminarInscripcionMousePressed

    private void jmiModificarMateriaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiModificarMateriaMousePressed
        GUIModificarMateria modMat = new GUIModificarMateria();
        modMat.setVisible(true);
        jDesktopPaneMain.add(modMat);
    }//GEN-LAST:event_jmiModificarMateriaMousePressed

    private void jmiBuscarAlumnoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiBuscarAlumnoMousePressed
        GUIBuscarAlumno buscarAlumno = new GUIBuscarAlumno();
        buscarAlumno.setVisible(true);
        jDesktopPaneMain.add(buscarAlumno);
    }//GEN-LAST:event_jmiBuscarAlumnoMousePressed

    private void jmiBuscarMateriaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiBuscarMateriaMousePressed
        GUIBuscarMateria buscarMateria = new GUIBuscarMateria();
        buscarMateria.setVisible(true);
        jDesktopPaneMain.add(buscarMateria);
    }//GEN-LAST:event_jmiBuscarMateriaMousePressed

    private void jmiModificarAlumnoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiModificarAlumnoMousePressed
        GUIModificarAlumno modAlum = new GUIModificarAlumno();
        modAlum.setVisible(true);
        jDesktopPaneMain.add(modAlum);
    }//GEN-LAST:event_jmiModificarAlumnoMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPaneMain;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenu_Alumnos;
    private javax.swing.JMenu jMenu_Inscripciones;
    private javax.swing.JMenu jMenu_Materias;
    private javax.swing.JMenuItem jmiAgregarAlumno;
    private javax.swing.JMenuItem jmiAgregarMateria;
    private javax.swing.JMenuItem jmiBuscarAlumno;
    private javax.swing.JMenuItem jmiBuscarMateria;
    private javax.swing.JMenuItem jmiEliminarInscripcion;
    private javax.swing.JMenuItem jmiModificarAlumno;
    private javax.swing.JMenuItem jmiModificarMateria;
    // End of variables declaration//GEN-END:variables
}
